# Generated by Django 4.0 on 2022-06-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentModel',
            fields=[
                ('development_id', models.AutoField(primary_key=True, serialize=False)),
                ('leader_id', models.IntegerField()),
                ('development_title', models.CharField(max_length=20)),
                ('development_activity', models.CharField(max_length=100)),
                ('development_budget', models.DecimalField(decimal_places=2, max_digits=100)),
                ('development_state', models.CharField(max_length=100)),
                ('development_activity_month', models.IntegerField(max_length=12)),
                ('development_activity_year', models.IntegerField(max_length=2040)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalLeaderModel',
            fields=[
                ('leader_id', models.AutoField(primary_key=True, serialize=False)),
                ('party_id', models.IntegerField()),
                ('candidate_name', models.CharField(max_length=20)),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalPartyModel',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=20)),
                ('party_founder', models.CharField(max_length=100)),
            ],
        ),
    ]
