# Generated by Django 4.0 on 2022-06-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentmodel',
            name='development_activity_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='developmentmodel',
            name='development_activity_year',
            field=models.IntegerField(),
        ),
    ]
